credentials:
  users:
    sampleuser:
      password: '123456'
      privileges:
        - permissions: [ read, write ]
          spaces: [ kv_storage ]
groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
                - uri: '127.0.0.1:3301'
app:
  file: 'init.lua'