
services:
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool
    command: tarantool /usr/local/share/tarantool/app.init.lua
    ports:
      - 3301:3301
    volumes:
      - ./init.lua:/usr/local/share/tarantool/app.init.lua
      - ./data:/var/lib/tarantool
      - ./config.yml:/etc/tarantool/config.yml

  storage:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_URL: "tarantool:3301"
    ports:
      - 8081:8081
    depends_on:
      - tarantool
    links:
      - tarantool
    networks:
      - default
    restart: on-failure:5


networks:
  net:
    driver: bridge
